export const Moods = {
  HAPPY: "HAPPY",
  SAD: "SAD",
  ANXIOUS: "ANXIOUS",
  NEUTRAL: "NEUTRAL",
  EXCITED: "EXCITED",
  ANGRY: "ANGRY",
  PEACEFUL: "PEACEFUL",
  GRATEFUL: "GRATEFUL",
  FRUSTRATED: "FRUSTRATED",
  WORRIED: "WORRIED",
  CONTENT: "CONTENT",
  TIRED: "TIRED",
};
