apiVersion: v1
kind: Secret
metadata:
  name: journai-app-secrets
  namespace: journai
type: Opaque
data:
  CLERK_SECRET_KEY: eW91cl9rZXk==
  CLERK_WEBHOOK_SECRET: eW91cl9rZXk==
  GEMINI_API_KEY: eW91cl9rZXk=
  NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: eW91cl9rZXk==
  CLERK_PUBLISHABLE_KEY: eW91cl9rZXk=